FROM ubuntu:22.04
ARG TARGETARCH

RUN apt-get update && apt-get install -y curl sudo gosu

RUN curl -fsSL "https://github.com/coder/code-server/releases/download/v4.23.0/code-server-4.23.0-linux-${TARGETARCH}.tar.gz" \
  | tar -xz -C /opt && \
  ln -s /opt-code-server-*/bin/code-server /usr/local/bin/code-server

# This COPY command now works because the file is in the same folder
COPY entrypoint.lab.sh /
RUN chmod +x /entrypoint.lab.sh

EXPOSE 8080
ENTRYPOINT ["/entrypoint.lab.sh"]